version: '3.5'
services:
  simple-jwt-provider:
    image: leberkleber/simple-jwt-provider
    restart: on-failure:5
    ports:
    - 8080:8080
    environment:
      SJP_SERVER_ADDRESS: ":8080"
      SJP_DB_HOST: "db"
      SJP_DB_PORT: 5432
      SJP_DB_NAME: "simple-jwt-provider"
      SJP_DB_USERNAME: "postgres"
      SJP_DB_PASSWORD: "postgres"
      SJP_DB_MIGRATIONS_FOLDER_PATH: "/db-migrations"
      SJP_ADMIN_API_ENABLE: "true"
      SJP_ADMIN_API_USERNAME: "username"
      SJP_ADMIN_API_PASSWORD: "password"
      SJP_JWT_PRIVATE_KEY: "\n-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIASzDZeTVLxcE5KTAmwrKwFjzr5cDrA+tttx9XRUz0K7AlROtj7cMG\nrHu/bdKj7lc2WaW8x/EOrU/FeCcsIL5nTH+gBwYFK4EEACOhgYkDgYYABAFBJr90\nWldGrPppBCbHqw2nGXeafxnSj6qB+A7E8A/G74mmmwIaqtf/pJ5QjqTPcAVUAEYF\nTz/0SPO3tPL1Ym3V0QH7TfnTf7EueabJqPdsSGR6uvbb2YOA9vy4OU8SXp/9a/4x\nr94giWgKjxYkB7xiy+IiZsWEBXU0rz7rb+IwJ82PfQ==\n-----END EC PRIVATE KEY-----"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "simple-jwt-provider"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"